name: 'download-workflow-artifacts'
description: 'Download artifacts from a completed workflow'
author: 'Keagan Soakell-Ho'
inputs:
  milliseconds:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
